config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'
  get 'welcome', to: 'pages#welcome'
  get 'custom_welcome/:first_name', to: 'pages#welcome', as: 'custom_welcome'
  get 'gossips/:id', to: 'gossips#show', as: 'gossip'


   # Routes for gossips
   resources :gossips

   # Routes for users (if using Devise or similar)
   resources :users, only: [:show, :new, :create]

  root 'pages#home'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_and_belongs_to_many :tags
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  has_many :recipients
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossip, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
# app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @gossips = Gossip.all
  end

  def team
  end

  def contact
  end

  def welcome
    @first_name = params[:first_name]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gossips/show.html.erb
<h1><%= @gossip.title %></h1>
<p><%= @gossip.content %></p>
<p>Créé par : <%= link_to @gossip.user.first_name, user_path(@gossip.user) %></p>
<p>Date de création : <%= @gossip.created_at %></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/team">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/welcome">Welcome</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Gossip Project</title>
  <!-- Ajouter les liens CDN de Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
  <%= render 'layouts/header' %> <!-- Inclure le header -->
  <%= yield %>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Contactez-nous</h1>
<p>Adresse e-mail : xavier.kerleau@gmail.com</p>

app/views/pages/home.html.erb
<!-- app/views/pages/home.html.erb -->
<h1>Bienvenue sur The Gossip Project !</h1>
<p>Ceci est la page d'accueil de notre application.</p>
<p>Vous pouvez voir tous les potins créés ici :</p>
<ul>
  <% @gossips.each do |gossip| %>
    <li>
      <%= link_to gossip.title, gossip_path(gossip) %> - <%= gossip.user.first_name %>
    </li>
  <% end %>
</ul>

app/views/pages/team.html.erb
<h1>Notre équipe</h1>
<p>Voici notre équipe lol mdr 😇❤️😻</p>

app/views/pages/welcome.html.erb
<h1>BIENVENUE <%= @first_name %> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>

app/views/users/show.html.erb
<h1>Profil de <%= @user.first_name %></h1>
<p>Nom : <%= @user.last_name %></p>
<p>Email : <%= @user.email %></p>